Release version 5.2.2-r3 (previous: 5.2.2-r2)

diff --git a/apk/renewal-hooks/deploy/01-zip b/apk/renewal-hooks/deploy/01-zip
--- a/apk/renewal-hooks/deploy/01-zip
+++ b/apk/renewal-hooks/deploy/01-zip
@@ -10,7 +10,16 @@
 . /usr/local/AppCentral/cappysan-certbot/.env.install
 cd ${APKG_CFG_DIR:-/nonexistent} || exit 1
 
-if test ! -e "${RENEWED_LINEAGE}"/privkey.pem; then
+if test "x${RENEWED_LINEAGE}" == "x"; then
+   RENEWED_LINEAGE=/etc/letsencrypt/live/$(certbot certificates 2>/dev/null | grep "Certificate Name:" | head -1 | cut -d":" -f2 | xargs)
+   echo RENEWED_LINEAGE=$RENEWED_LINEAGE
+fi
+
+if test "x${RENEWED_LINEAGE}" == "x"; then
+  echo "Skipping, RENEWED_LINEAGE is not set" >&2
+  exit 1
+elif test ! -e "${RENEWED_LINEAGE}"/privkey.pem; then
+  echo "Skipping, keys not found in ${RENEWED_LINEAGE} directory" >&2
   exit 1
 fi
 
@@ -18,7 +27,9 @@ fi
 export PATH=$PATH:/usr/builtin/bin/
 
 rm -f ${APKG_CFG_DIR}/certificates.zip 2>/dev/null
-zip ${APKG_CFG_DIR}/certificates.zip last_run
+if test -f last_run; then
+  zip ${APKG_CFG_DIR}/certificates.zip last_run
+fi
 (cd "${RENEWED_LINEAGE}" && zip ${APKG_CFG_DIR}/certificates.zip cert.pem chain.pem fullchain.pem privkey.pem)
 
 chown admin:root ${APKG_CFG_DIR}/certificates.zip
diff --git a/apk/renewal-hooks/deploy/lighthttpd b/apk/renewal-hooks/deploy/lighthttpd
--- a/apk/renewal-hooks/deploy/lighthttpd
+++ b/apk/renewal-hooks/deploy/lighthttpd
@@ -3,16 +3,28 @@
 . /usr/local/AppCentral/cappysan-certbot/.env.install
 cd ${APKG_CFG_DIR:-/nonexistent} || exit 1
 
+if test "x${RENEWED_LINEAGE}" == "x"; then
+   RENEWED_LINEAGE=/etc/letsencrypt/live/$(certbot certificates 2>/dev/null | grep "Certificate Name:" | head -1 | cut -d":" -f2 | xargs)
+   echo RENEWED_LINEAGE=$RENEWED_LINEAGE
+fi
+
 # We need openssl
 export PATH=$PATH:/usr/builtin/bin/
 
 # If issuer is Asustor, then our certificates are not installed
-if openssl x509 -noout -text -in  /usr/builtin/etc/certificate/ssl.crt | grep Issuer | grep -q Asustor; then
+if test "x${RENEWED_LINEAGE}" == "x"; then
+  echo "Skipping, RENEWED_LINEAGE is not set" >&2
   exit 1
-fi
-if openssl x509 -noout -text -in "${RENEWED_LINEAGE}"/cert.pem | grep Issuer | grep -q "Let's Encrypt"; then
+elif openssl x509 -noout -text -in  /usr/builtin/etc/certificate/ssl.crt | grep Issuer | grep -q Asustor; then
+  echo "Certificate is from Asustor, not restarting lighthttpd" >&2
+  exit 1
+elif test ! -f "${RENEWED_LINEAGE}"/cert.pem; then
+  echo "Certificates not found in ${RENEWED_LINEAGE}, not restarting lighthttpd" >&2
+  exit 1
+elif openssl x509 -noout -text -in "${RENEWED_LINEAGE}"/cert.pem | grep Issuer | grep -q "Let's Encrypt"; then
   true
 else
+  echo "Certificate is neither from Asustor nor Let's Encrypt, not restarting lighthttpd" >&2
   exit 1
 fi
 
