Prepare new release with renaming

diff --git a/apk/bin/certbot-init b/apk/bin/certbot-init
--- a/apk/bin/certbot-init
+++ b/apk/bin/certbot-init
@@ -3,40 +3,48 @@
 # NAME
 #      certbot-init - create the certificates
 #
-syslog --log 0 --level 0 --user SYSTEM --event "Initializing certbot certificates..."
+as_cfg=/share/Configuration/certbot
 
-as_cfg=/share/Configuration/certbot-dns
-if ! test -f "${as_cfg}/active"; then
-  syslog --log 0 --level 1 --user SYSTEM --event "Certbot certificates are deactivated."
+function logger() {
+  echo "${@}" >&2
+  syslog --log 0 --level 0 --user SYSTEM --event "${@}"
+}
+logger "Initializing certbot certificates..."
+
+if test ! -f "${as_cfg}/active"; then
+  logger "Certbot certificates are deactivated."
   exit 0
 fi
 
 # For every renewal hook that we find, install it before deploy section.
 for as_hook in /usr/local/AppCentral/*/renewal-hooks/deploy/*; do
-  cp -f "${as_hook}" /usr/local/AppCentral/cappysan-certbot-dns/renewal-hooks/deploy/
+  # Overwrite since it could be more recent
+  cp -f "${as_hook}" /usr/local/AppCentral/cappysan-certbot/renewal-hooks/deploy/
 done
 
-rm -fr /etc/letsencrypt
+if test -d /etc/letsencrypt; then
+  rm -fr /etc/letsencrypt
+fi
 mkdir -p ${as_cfg}/letsencrypt
 ln -sf -T ${as_cfg}/letsencrypt /etc/letsencrypt
 
+email=$(head -c10 /dev/urandom | md5sum | head -c10)@gmail.com
 domains="$(cat ${as_cfg}/domains.conf)"
-method="$(cat ${as_cfg}/method.conf)"
+commandline="$(cat ${as_cfg}/commandline.conf)"
 
 # Use --manual-auth-hook and --manual-cleanup-hook?
-email=$(head -c10 /dev/urandom | md5sum | head -c10)@gmail.com
-
-syslog --log 0 --level 0 --user SYSTEM --event "Requesting new certificate..."
-echo /usr/local/AppCentral/cappysan-certbot-dns/bin/certbot certonly "${@}" -n -m "${email}" --agree-tos ${method} -d "${domains}" >&2
-if /usr/local/AppCentral/cappysan-certbot-dns/bin/certbot certonly "${@}" -n -m "${email}" --agree-tos ${method} -d "${domains}" 2>&1 | tee /tmp/certbot.log; then
+logger "Requesting new certificate..."
+echo /usr/local/AppCentral/cappysan-certbot/bin/certbot certonly "${@}" -n -m "${email}" --agree-tos ${commandline} -d "${domains}" >&2
+if /usr/local/AppCentral/cappysan-certbot/bin/certbot certonly "${@}" -n -m "${email}" --agree-tos ${commandline} -d "${domains}" 2>&1 | tee /tmp/certbot.log; then
   if grep -q 'no action taken.' /tmp/certbot.log; then
-    syslog --log 0 --level 0 --user SYSTEM --event "Requesting new certificate: Success. Certificate not due for renewal."
+    logger "Requesting new certificate: Success. Certificate not due for renewal."
   elif grep -q 'unexpected error' /tmp/certbot.log; then
-    syslog --log 0 --level 0 --user SYSTEM --event "Requesting new certificate: Success. Certificate generation error."
+    logger "Requesting new certificate: Success. Certificate generation error."
   else
-    syslog --log 0 --level 0 --user SYSTEM --event "Requesting new certificate: Success. Certificate renewed."
+    logger "Requesting new certificate: Success."
     date > ${as_cfg}/last_run
   fi
 else
+  echo "${@}" >&2
   syslog --log 0 --level 1 --user SYSTEM --event "Requesting new certificate: Failure"
 fi
diff --git a/apk/bin/certbot-renew b/apk/bin/certbot-renew
--- a/apk/bin/certbot-renew
+++ b/apk/bin/certbot-renew
@@ -7,15 +7,17 @@
 #
 #   --force-renewal    Force the renewal of the certificate
 #
-as_cfg=/share/Configuration/certbot-dns
+as_cfg=/share/Configuration/certbot
+
+function logger() {
+  echo "${@}" >&2
+  syslog --log 0 --level 0 --user SYSTEM --event "${@}"
+}
+
 if test ! -f "${as_cfg}/active"; then
+  logger "Certbot certificates are deactivated."
   exit 0
 fi
-
-# For every renewal hook that we find, install it before deploy section.
-for as_hook in /usr/local/AppCentral/*/renewal-hooks/deploy/*; do
-  cp -f "${as_hook}" /usr/local/AppCentral/cappysan-certbot-dns/renewal-hooks/deploy/
-done
 
 # Always reset the permissions
 chown root:root ${as_cfg}/
@@ -23,12 +25,26 @@ chmod 700 ${as_cfg}/
 chown root:root ${as_cfg}/*.conf
 chmod 600 ${as_cfg}/*.conf
 
+# last_run records last success
 if test ! -f ${as_cfg}/last_run; then
-  exec /usr/local/AppCentral/cappysan-certbot-dns/bin/certbot-init "${@}"
+  exec /usr/local/AppCentral/cappysan-certbot/bin/certbot-init "${@}"
 fi
 
-syslog --log 0 --level 0 --user SYSTEM --quiet --event "Requesting certificate renewal..."
-echo /usr/local/AppCentral/cappysan-certbot-dns/bin/certbot -q renew --no-random-sleep-on-renew "${@}" >&2
-if /usr/local/AppCentral/cappysan-certbot-dns/bin/certbot -q renew --no-random-sleep-on-renew "${@}"; then
-  date > ${as_cfg}/last_run
+# For every renewal hook that we find, install it before deploy section.
+for as_hook in /usr/local/AppCentral/*/renewal-hooks/deploy/*; do
+  cp -f "${as_hook}" /usr/local/AppCentral/cappysan-certbot/renewal-hooks/deploy/
+done
+
+logger "Requesting certificate renewal..."
+echo /usr/local/AppCentral/cappysan-certbot/bin/certbot renew --no-random-sleep-on-renew "${@}" >&2
+if /usr/local/AppCentral/cappysan-certbot/bin/certbot renew --no-random-sleep-on-renew "${@}" 2>&1 | tee /tmp/certbot.log ; then
+  if grep -q 'Certificate not yet due for renewal' /tmp/certbot.log; then
+    logger "Rewewing certificate: Pass. Certificate not due for renewal."
+  else
+    logger "Renewing certificate: Success."
+    date > ${as_cfg}/last_run
+  fi
+else
+  echo "${@}" >&2
+  syslog --log 0 --level 1 --user SYSTEM --event "Renewing certificate: Failure"
 fi
